//! Conventional Commit messages and pull-request bodies for fract refactors.
//!
//! Renders data the daemon already collects — refactor kind, module, confidence,
//! the [`ValidationReport`], migration notes, and the [`DiffSummary`] — into
//! stable, review-ready text. No git mutation happens here; this is pure
//! presentation on top of a [`Proposal`].

use crate::{Proposal, ValidationReport};

/// Build a Conventional Commit message (subject + body) for a proposal.
pub fn conventional_commit_message(p: &Proposal) -> String {
    let scope = p
        .module
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("module");
    let subject = format!("refactor({}): {}", scope, p.kind.to_string().to_lowercase());

    let mut out = subject;
    out.push_str(&format!(
        "\n\nmodule: {}\nconfidence: {:.0}%\n",
        p.module.display(),
        p.confidence * 100.0
    ));
    out.push_str(&format!(
        "changes: +{} -{} across {} file(s)\n",
        p.diff_summary.lines_added,
        p.diff_summary.lines_removed,
        p.diff_summary.files_added + p.diff_summary.files_modified + p.diff_summary.files_removed
    ));
    if !p.migration_notes.is_empty() {
        out.push_str("\nmigration notes:\n");
        for n in &p.migration_notes {
            out.push_str(&format!("- {n}\n"));
        }
    }
    out
}

/// Render a Markdown pull-request body. `branch` and `sha` may be empty in
/// assisted mode (changes left uncommitted on the branch).
pub fn render_pr_body(p: &Proposal, diff: &str, branch: &str, sha: &str) -> String {
    use std::fmt::Write;
    let mut out = String::new();

    let _ = writeln!(out, "## fract: {} on `{}`", p.kind, p.module.display());
    let _ = writeln!(out);
    let _ = writeln!(out, "**Kind:** {}  ", p.kind);
    let _ = writeln!(out, "**Confidence:** {:.0}%  ", p.confidence * 100.0);
    if !branch.is_empty() {
        let _ = writeln!(out, "**Branch:** `{branch}`  ");
    }
    if !sha.is_empty() {
        let _ = writeln!(out, "**Commit:** `{}`", short(sha));
    }
    let _ = writeln!(out);

    if let Some(v) = &p.validation {
        let _ = writeln!(out, "{}", validation_line(v));
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "### Changes");
    let _ = writeln!(out, "- Files added: {}", p.diff_summary.files_added);
    let _ = writeln!(out, "- Files modified: {}", p.diff_summary.files_modified);
    let _ = writeln!(
        out,
        "- Lines: +{} / -{}",
        p.diff_summary.lines_added, p.diff_summary.lines_removed
    );

    if !p.migration_notes.is_empty() {
        let _ = writeln!(out, "\n### Migration notes");
        for n in &p.migration_notes {
            let _ = writeln!(out, "- {n}");
        }
    }

    if !diff.trim().is_empty() {
        let _ = writeln!(out, "\n### Diff");
        let _ = writeln!(out, "<details><summary>unified diff</summary>\n");
        let _ = writeln!(out, "```diff");
        let _ = writeln!(out, "{}", diff.trim_end());
        let _ = writeln!(out, "```");
        let _ = writeln!(out, "</details>");
    }

    let _ = writeln!(out, "\n### Rollback");
    if !sha.is_empty() {
        let _ = writeln!(out, "```\ngit revert {}\n```", short(sha));
    } else if !branch.is_empty() {
        let _ = writeln!(out, "```\ngit checkout - && git branch -D {branch}\n```");
    } else {
        let _ = writeln!(
            out,
            "Discard the working-tree changes for `{}`.",
            p.module.display()
        );
    }

    let _ = writeln!(
        out,
        "\n---\n*Generated by fract ({})*",
        crate::report::SCHEMA
    );
    out
}

fn validation_line(v: &ValidationReport) -> String {
    let mark = |b: bool| if b { "✓" } else { "✗" };
    format!(
        "**Validation:** fmt {} · clippy {} · check {} · test {} · api {}",
        mark(v.fmt_ok),
        mark(v.clippy_ok),
        mark(v.check_ok),
        mark(v.test_ok),
        mark(v.api_compatible)
    )
}

fn short(sha: &str) -> &str {
    &sha[..sha.len().min(12)]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::time::now;
    use crate::{DiffSummary, ProposalStatus, RefactorKind};
    use std::path::PathBuf;

    fn sample() -> Proposal {
        Proposal {
            id: "fract-1".to_string(),
            created_at: now(),
            module: PathBuf::from("src/lib.rs"),
            kind: RefactorKind::SplitModule,
            confidence: 0.88,
            status: ProposalStatus::Accepted,
            validation: Some(ValidationReport {
                fmt_ok: true,
                clippy_ok: true,
                check_ok: true,
                test_ok: false,
                api_compatible: true,
                coverage_delta: 0.0,
                complexity_delta: -0.1,
                logs: vec![],
            }),
            diff_summary: DiffSummary {
                files_added: 1,
                files_removed: 0,
                files_modified: 1,
                lines_added: 40,
                lines_removed: 120,
            },
            migration_notes: vec!["keep public API".to_string()],
            changed_files: vec![],
            pr_body: None,
            timeline: vec![],
        }
    }

    #[test]
    fn commit_message_has_scope_confidence_and_notes() {
        let msg = conventional_commit_message(&sample());
        assert!(msg.starts_with("refactor(lib): split responsibilities into submodules"));
        assert!(msg.contains("confidence: 88%"));
        assert!(msg.contains("+40 -120"));
        assert!(msg.contains("- keep public API"));
    }

    #[test]
    fn pr_body_renders_validation_notes_diff_and_rollback() {
        let diff = "diff --git a/src/lib.rs b/src/lib.rs\n@@ -1 +1 @@\n-old\n+new\n";
        let body = render_pr_body(&sample(), diff, "fract/1", "abcdef1234567890");
        assert!(body.contains("Split responsibilities into submodules"));
        assert!(body.contains("fmt ✓"));
        assert!(body.contains("test ✗"));
        assert!(body.contains("- keep public API"));
        assert!(body.contains("```diff"));
        assert!(body.contains("git revert abcdef123456"));
        assert!(body.contains("fract.report/v1"));
    }

    #[test]
    fn pr_body_without_sha_falls_back_to_branch_rollback() {
        let body = render_pr_body(&sample(), "", "fract/1", "");
        assert!(body.contains("git branch -D fract/1"));
        assert!(!body.contains("git revert"));
    }
}
